Refactor: Calculate invoice expiry outside of the crud
lnbits/lnbits pull request #1849
Opened 2023-08-03 09:54 UTC by callebtc

2023-08-03 10:21 UTC, dni approved these changes

2023-10-09 15:18 UTC, prusnak commented
Resolved the conflicts and rebased on top of the `dev` branch.

2023-10-10 06:27 UTC, motorina0 commented on lnbits/core/crud.py
> -from bolt11.decode import decode
- what a blasphemy!

2023-10-10 06:39 UTC, motorina0 commented on lnbits/core/services.py
> +            expiry=invoice_expiry,
- nitpick: is a variable for `invoice_expiry` required?
```suggestion
            expiry=get_bolt11_expiry(payment_request),
```

2023-10-10 06:40 UTC, motorina0 submitted a review, later dismissed

2023-10-10 06:58 UTC, dni approved these changes

2023-10-10 07:01 UTC, dni requested changes
![screenshot-1696921282](https://github.com/lnbits/lnbits/assets/1743657/54bdc493-9cd4-4c35-9eb3-b64c521f1702)

2023-10-10 08:59 UTC, dni approved these changes
1 expiry on create_payment was missing, works now for me

2023-10-10 10:00 UTC, motorina0 approved these changes

2023-10-10 10:03 UTC, merged