Fix nix build and modules
lnbits/lnbits pull request #1855
Opened 2023-08-04 21:42 UTC by HaosGames

This fixes the out of date nix build configuration and modules. 

Some things that still need fixing:
- [ ] creation of `.super-user` file failes due to read only file system in the store. That means that you can't use the admin ui yet. 
- [ ] installation of extensions via the ui failes because the extensions dir is also in the read-only store

2023-08-13 15:48 UTC, HaosGames commented
Actually I will need to leave those two points for another PR. At this point I cant figure out how to fix these.

2023-08-22 16:49 UTC, dni commented
is it still a wip? or is it mergeable?

2023-08-22 17:17 UTC, prusnak requested changes

2023-08-22 17:17 UTC, prusnak commented on nix/modules/lnbits-service.nix
> +      "d ${cfg.extensionsDir}                        0700 ${cfg.user} ${cfg.group} - -"
drop extra space:
```suggestion
      "d ${cfg.extensionsDir}                       0700 ${cfg.user} ${cfg.group} - -"
```

2023-08-22 17:17 UTC, prusnak commented on flake.nix
> +          config.permittedInsecurePackages = [
Let's not deal with this here, but let's fix cashu upstream and then use the fixed version of the upstream.

2023-08-22 17:17 UTC, prusnak commented on flake.nix
> +                nativeBuildInputs = (old.nativeBuildInputs or [ ]) ++ [ (import legacy-nixpkgs {inherit system;}).python3Packages.setuptools ];
Let's not deal with this here, but let's fix cashu upstream and then use the fixed version of the upstream.

2023-08-22 17:17 UTC, prusnak commented on flake.nix
> +          nativeBuildInputs = [(import legacy-nixpkgs {inherit system;}).python3Packages.setuptools];
Please don't. If there is an issue, let's fix it, but importing old version is just nasty.

2023-10-03 16:44 UTC, prusnak commented
This PR is a total mess because the main branch is no longer used for development but for a stable release.

Also https://github.com/lnbits/lnbits/pull/1979 which fixes the nix stuff has been merged.

I am closing this PR.

If something still needs fixing, please open a new PR.

2023-10-03 16:44 UTC, closed without merging