[REFACTOR] replace async_wrap with run_sync
lnbits/lnbits pull request #1858
Opened 2023-08-07 07:33 UTC by dni

cleans up code and needed for cln to be shutdown properly.

2023-08-07 11:23 UTC, motorina0 approved these changes

2023-08-23 10:49 UTC, callebtc requested changes
Possibly unrelated code.

2023-08-23 10:49 UTC, callebtc commented on Makefile
> +	sleep 15
Unrelated?

2023-08-23 10:49 UTC, callebtc commented on lnbits/server.py
> -
Unrelated?

2023-08-23 16:39 UTC, jackstar12 commented on lnbits/server.py
> -
no, see: https://github.com/lnbits/lnbits/pull/1860/commits/42067945e5da4afbdc07271b1ad3784c5d56abc6

2023-08-24 14:26 UTC, jackstar12 approved these changes

2023-08-25 12:10 UTC, talvasconcelos approved these changes
tested.

2023-08-28 09:59 UTC, merged