[REFACTOR] WalletType into enum
lnbits/lnbits pull request #1888
Opened 2023-08-19 08:16 UTC by dni

- move wallettype models from decorators.py into models.py
- use enum instead of int
- use HTTPStatus for consistency

2023-08-21 09:23 UTC, jackstar12 requested changes

2023-08-21 09:23 UTC, jackstar12 commented on lnbits/core/models.py
> +        self.wallet = wallet
This could be a dataclass or typedenum to get rid of the `__init__`

2023-08-21 14:44 UTC, jackstar12 approved these changes

2023-08-23 10:41 UTC, callebtc commented
Love it.

2023-08-23 10:41 UTC, callebtc approved these changes

2023-08-23 10:41 UTC, merged