wallets/lndrest_catch_http_errors
lnbits/lnbits pull request #2030
Opened 2023-10-13 17:09 UTC by callebtc

This PR catches the errors in `lndrest.py` that can happen when for example the LND certificate has expired. 

This can lead to stuck payments.

2023-10-13 18:30 UTC, dni approved these changes

2023-10-15 08:41 UTC, prusnak requested changes
CI is failing

2023-10-16 05:33 UTC, dni commented
the PR was based on `main` branch not `dev`, switching it made this mess of conflicts.

2023-10-26 12:21 UTC, callebtc commented
Replaced by #2062 2062

2023-10-26 12:21 UTC, closed without merging