WIP: Add service fee to specific wallet
lnbits/lnbits pull request #2050
Opened 2023-10-18 13:37 UTC by callebtc

2023-11-10 11:12 UTC, callebtc commented
`service_fee` should probably be included in `fee_reserve` so that external modules can call it to get the actual fee required now. `fee_reserve` itself should probably include a check whether a payment is internal or not. otherwise it's going to get more complicated for an extension (say splitpayment) to figure out things like: 

- is this an internal payment?
- if yes, is there a fee reserve?
- is there a service fee?
- if there a service fee for internal payments?

All this should be abstracted away from an external module.

2023-11-13 18:15 UTC, prusnak requested changes

2023-11-13 18:15 UTC, prusnak commented on .env.example
> +# Max fee to charge, 0 will leave no max and use LNBITS_SERVICE_FEE %
```suggestion
# Max fee to charge per transaction (in satoshi), 0 will leave no max and use LNBITS_SERVICE_FEE %
```

2023-11-13 18:15 UTC, prusnak commented on lnbits/core/services.py
> +    service_fee_percent = settings.lnbits_service_fee
The comment in `.env.example` says that "1.0" is "100% fee", so the fee is not specified in percent.

We need to either fix the code or the comment.

2023-11-17 15:04 UTC, prusnak approved these changes
not fully understood the math in `lnbits/core/services.py` but the rest looks OK, untested ACK

2023-11-21 10:04 UTC, dni approved these changes

2023-11-21 11:11 UTC, merged