Add Cashu wallet backend
lnbits/lnbits pull request #2063
Opened 2023-10-26 12:47 UTC by callebtc

Adds Cashu wallet backend through the REST API.

Depends on https://github.com/cashubtc/nutshell/pull/318

2023-10-26 13:52 UTC, prusnak requested changes
untested, code looks good

2023-10-26 13:52 UTC, prusnak approved these changes
untested, code looks good

2023-10-27 11:45 UTC, dni commented on lnbits/wallets/cashu.py
> +        #     logger.warning(f"Error closing wallet connection: {e}")
any reason for why not cleaning up the client?

2024-02-09 09:17 UTC, dni commented
@callebtc the required PR seems to be merged, can you take a look again?

2024-02-13 13:34 UTC, motorina0 commented
@callebtc 
 - is this PR completed
 - is there a `cashu` docker image that we can use in our regtest

2024-08-30 11:53 UTC, arcbtc commented
Bump @callebtc. Lets get this out of draft and ready to merge

2024-10-01 20:07 UTC, callebtc commented
I won't have time to finish this PR unfortunately

2024-10-01 20:07 UTC, closed without merging