Enable Node Management via .env without activating admin-UI
lnbits/lnbits pull request #2068
Opened 2023-10-26 20:16 UTC by TrezorHannes

The recent Node Management feature is only available if you set `LNBITS_ADMIN_UI=true`. 
For LNBITS users who keep running their instance managing their `.env` file, the following PR would allow them to use the feature and adjust settings without the UI.

This can be looked up at the boolean settings blurp [over here](https://github.com/lnbits/lnbits/blob/fed2d411399a0f3f46c1fffe5f6f67942e56b2e7/lnbits/settings.py#L236), and has been tested on a production node.

What is missing is the "Node" menu entry on the left navigation bar. The overview can be retrieved by browsing to https://yourdomain.com/**node**?user=1233434555564, but adding this navigation bar  as soon one of 
```
LNBITS_NODE_UI=false 
LNBITS_PUBLIC_NODE_UI=false
LNBITS_NODE_UI_TRANSACTIONS=false
```
is `true` would make the usability much more elegant. But this isn't included in the PR and would need to be added into the UI Templates

2023-10-27 21:35 UTC, prusnak requested changes

2023-10-27 21:35 UTC, prusnak commented on .env.example
> +.
typo
```suggestion

```

2023-10-28 08:34 UTC, TrezorHannes commented on .env.example
> +.
Oops

2023-10-28 08:36 UTC, TrezorHannes reviewed
Thanks for your review, LGTM

2023-10-28 14:13 UTC, prusnak approved these changes

2023-10-28 16:36 UTC, jackstar12 requested changes

2023-10-28 16:36 UTC, jackstar12 commented on .env.example
> +# Be aware that setting this true can add additional stress to weaker hardware
```suggestion
# Enabling the transactions tab can cause crashes on large cln nodes.
```

2023-10-28 20:07 UTC, jackstar12 approved these changes

2023-10-28 20:07 UTC, merged