Fixed payment isn't initiated on lndrest
lnbits/lnbits pull request #2074
Opened 2023-10-30 15:24 UTC by skrafft

2023-10-30 22:38 UTC, prusnak requested changes

2023-10-30 22:38 UTC, prusnak commented on lnbits/wallets/lndrest.py
> +                        if line["error"]["code"] == 5 and line["error"]["message"] == "payment isn't initiated":
I think the following is more correct:

```suggestion
                        if line["error"].get("code") == 5 and line["error"].get("message") == "payment isn't initiated":
```

2023-10-31 06:52 UTC, skrafft commented
@prusnak Thanks, I changed the PR

2023-10-31 09:56 UTC, callebtc commented
Nice one. Could you please run the formatter? `make format` and push again please.

2023-10-31 10:04 UTC, skrafft commented
Done, sorry for the mistake

2023-11-01 15:06 UTC, dni approved these changes

2023-11-01 17:03 UTC, prusnak commented
@callebtc I don't understand the edit in the original post - does that mean that this PR supersedes PR https://github.com/lnbits/lnbits/pull/2062?

2023-11-03 18:30 UTC, prusnak approved these changes

2023-11-03 18:31 UTC, prusnak commented
> #2062

I think this should close https://github.com/lnbits/lnbits/issues/1913 not https://github.com/lnbits/lnbits/pull/2062

2023-11-12 21:53 UTC, merged