fix issue with displaying languages
lnbits/lnbits pull request #2130
Opened 2023-11-28 11:05 UTC by talvasconcelos

When using `delimiters` to avoid the `{% raw %}` stuff, the toolbar, which is rendered on the base html doesn't display languages correctly.

- refactored the language list to show correctly

2023-11-28 11:23 UTC, prusnak commented
The issue is present also at the bottom of the TPOS extension (LNbits version and link to API docs), see:

![tpos](https://github.com/lnbits/lnbits/assets/42201/e224b3dd-42d0-43a3-833e-d2eb824731c0)

2023-11-28 11:24 UTC, prusnak commented
Also the dark mode tooltip:

<img width="161" alt="Screenshot 2023-11-28 at 12 24 21" src="https://github.com/lnbits/lnbits/assets/42201/903fd94d-a56c-4fca-812f-060d5d0bfefb">

2023-11-28 11:32 UTC, prusnak requested changes

2023-11-28 12:43 UTC, prusnak commented
Btw, why does this only affect TPOS extension and not the others?

2023-11-28 13:02 UTC, dni commented
it should be fixed in tpos, imho, but also here it nicer to have it like that.

2023-11-28 19:40 UTC, prusnak commented
There are more extensions that have the same issue, so we should either fix it in LNbits core or we fix all the extensions:
* tpos
* satspay
* boltcards

2023-11-30 09:05 UTC, dni commented on lnbits/templates/base.html
> -                  <q-tooltip>{{lang.label}}</q-tooltip>
readded

2023-11-30 11:01 UTC, dni approved these changes

2023-11-30 11:52 UTC, prusnak requested changes

2023-11-30 11:52 UTC, prusnak commented on lnbits/templates/base.html
> +            v-text="$t('api_docs')"
It seems this line removed the tooltip inside.

2023-11-30 12:46 UTC, prusnak approved these changes

2023-11-30 12:55 UTC, merged