CLN: paymentstate check on error
lnbits/lnbits pull request #2151
Opened 2023-12-05 10:07 UTC by callebtc

2023-12-05 10:12 UTC, prusnak submitted a review, later dismissed
CI failure: https://github.com/lnbits/lnbits/actions/runs/7099157921/job/19322647760?pr=2151

2023-12-06 16:53 UTC, dni requested changes
i am scared, i think also the debug log when deleting was removed,and that actually saved us this time discovering the issue at all. so at least the log should be readded.

2023-12-06 17:02 UTC, prusnak commented
> i am scared, i think also the debug log when deleting was removed

It was re-added in 7dfbabf

2023-12-19 10:55 UTC, dni commented on lnbits/core/models.py
>          # wait at least 15 minutes before deleting failed outgoing payments
```suggestion
```

2023-12-19 10:57 UTC, dni approved these changes

2023-12-19 15:08 UTC, prusnak commented
Squashed and rebased

2024-03-12 10:43 UTC, talvasconcelos approved these changes

2024-03-12 12:31 UTC, motorina0 approved these changes

2024-03-12 12:56 UTC, merged