feat: lnurl library update
lnbits/lnbits pull request #2153
Opened 2023-12-05 14:04 UTC by dni

follow up on https://github.com/lnbits/lnbits/pull/1864/files

2023-12-05 23:38 UTC, prusnak requested changes
Let's merge this PR first: https://github.com/lnbits/lnbits/pull/2156

I will then update this PR to build on nix properly.

2023-12-06 09:36 UTC, motorina0 approved these changes

2023-12-06 09:36 UTC, motorina0 commented
Tested with TPOS: ok

2023-12-06 11:06 UTC, prusnak requested changes
Let's wait with the merge until https://github.com/nix-community/poetry2nix/pull/1449 is merged - then I will fix up nix build properly (shouldn't take long hopefully, maintainers of poetry2nix are very responsive).

2023-12-06 11:54 UTC, prusnak approved these changes

2023-12-06 11:55 UTC, merged